### ISSUE TITLE
Expose Docker registry

### ISSUE THREAD

**Issue by hekonsek** [hekonsek/streamshift#1]
We need to expose `docker-registry` service to the outside world in openshift.yml [1], via `oc expose` or something similar.

[1] https://github.com/hekonsek/streamshift/blob/master/openshift/openshift.yml

**Comment by hekonsek** [comment]
Here is the service to expose:

```
oc get service
NAME              CLUSTER-IP       EXTERNAL-IP   PORT(S)                 AGE
docker-registry   172.30.241.205   <none>        5000/TCP                32m

```

**Comment by ajurasz** [comment]
[Documentation](https://docs.openshift.com/container-platform/3.3/install_config/registry/securing_and_exposing_registry.html) from OpenShift.

**Comment by ajurasz** [comment]
Done
